//To install:
//go get -u github.com/andelf/go-curl

package main

import (
    "net/http"
    "io/ioutil"
)

func main() {

    // Generated by curl-to-Go: https://mholt.github.io/curl-to-go
    resp, err := http.Get("http://inapplet.com/")
    if err != nil {
    	// handle err
    }
    defer resp.Body.Close()
    
    defer resp.Body.Close()
    body, err := ioutil.ReadAll(resp.Body)
    
    // write the whole body at once
    err = ioutil.WriteFile("output.txt", body, 0644)
    if err != nil {
        panic(err)
    }
}