//To install:
//go get -u github.com/andelf/go-curl

package main

import (
    "net/http"
)

func main() {

    // Generated by curl-to-Go: https://mholt.github.io/curl-to-go
    resp, err := http.Get("http://inapplet.com/")
    if err != nil {
    	// handle err
    }
    defer resp.Body.Close()
}